# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Default task that runs when no task is specified
    deps:
      - task: push

  push:
    desc: Push changes to the remote repository
    cmds:
      - git push origin
      - git push gitee
